USE [master]
GO
 Object  Database [JsonTst]    Script Date 19.1.2022 9.30.10 
CREATE DATABASE [JsonTst]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'JsonTst', FILENAME = N'CProgram FilesMicrosoft SQL ServerMSSQL15.KTLT025AMSSQLDATAJsonTst.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'JsonTst_log', FILENAME = N'CProgram FilesMicrosoft SQL ServerMSSQL15.KTLT025AMSSQLDATAJsonTst_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [JsonTst] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [JsonTst].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [JsonTst] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [JsonTst] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [JsonTst] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [JsonTst] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [JsonTst] SET ARITHABORT OFF 
GO
ALTER DATABASE [JsonTst] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [JsonTst] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [JsonTst] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [JsonTst] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [JsonTst] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [JsonTst] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [JsonTst] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [JsonTst] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [JsonTst] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [JsonTst] SET  ENABLE_BROKER 
GO
ALTER DATABASE [JsonTst] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [JsonTst] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [JsonTst] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [JsonTst] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [JsonTst] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [JsonTst] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [JsonTst] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [JsonTst] SET RECOVERY FULL 
GO
ALTER DATABASE [JsonTst] SET  MULTI_USER 
GO
ALTER DATABASE [JsonTst] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [JsonTst] SET DB_CHAINING OFF 
GO
ALTER DATABASE [JsonTst] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [JsonTst] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [JsonTst] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'JsonTst', N'ON'
GO
ALTER DATABASE [JsonTst] SET QUERY_STORE = OFF
GO
USE [JsonTst]
GO
 Object  Table [dbo].[Attributes]    Script Date 19.1.2022 9.30.10 
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Attributes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Attribute] [nvarchar](max) NULL,
	[EmailKey] [nvarchar](max) NULL,
 CONSTRAINT [PK_Attributes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
 Object  Table [dbo].[Congrats]    Script Date 19.1.2022 9.30.10 
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Congrats](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[EmailAddress] [nvarchar](max) NOT NULL,
	[EmailBody] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Congrats] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
 Object  Table [dbo].[Emails]    Script Date 19.1.2022 9.30.10 
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Emails](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Key] [nvarchar](450) NOT NULL,
	[Email] [nvarchar](max) NULL,
	[Date] [date] NOT NULL,
	[Attribute] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Emails] ADD  CONSTRAINT [DF_Emails_Date]  DEFAULT (getdate()) FOR [Date]
GO
USE [master]
GO
ALTER DATABASE [JsonTst] SET  READ_WRITE 
GO